version: '3'

services:

  back-end:
    build:
      context: server
    container_name: back-end
    working_dir: /usr/src/app
    networks:
      - tbaza_network
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "5000:5000"
    command: npm run dev
    depends_on:
       - db

  front-end:
    build:
      context: client
    container_name: front-end
    working_dir: /usr/src/app
    networks:
      - tbaza_network
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    command: npm start

  db:
    build:
      context: client
    container_name: db
    restart: always
    tty: true
    ports:
      - "27017:27017"
    networks:
      - tbaza_network

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    networks:
      - tbaza_network
    depends_on:
       - back-end
       - front-end

networks:
  tbaza_network:
    driver: bridge
